### ISSUE TITLE
datasets/illustration.txt

### ISSUE THREAD

**Issue by learn-by-consciousness** [kia-kia/IC-MLNet#1]
http://data.cma.cn/en/?r=data/detail\&dataCode=A.0012.0001/
should be
http://data.cma.cn/en/?r=data/detail&dataCode=A.0012.0001

**Comment by learn-by-consciousness** [comment]
http://data.cma.cn/en/?r=data/detail&dataCode=A.0012.0001

**Comment by xufy9** [comment]
oh, thank you. Now it's correct.

**Comment by learn-by-consciousness** [comment]
你的邮件已收到，谢谢！
